In [ ]:
import numpy as np
import tensorflow as tf

def partial_transpose(rho, subsys='B'):
    """
    Helper function to compute the partial transpose of a density matrix. 
    Useful for the Peres-Horodecki criterion, which states that if the partial transpose 
    of a density matrix has at least one negative eigenvalue, then the state is entangled.
    
    Parameters:
        rho: density matrix
        subsys: which subsystem to compute partial transpose wrt, i.e. 'A' or 'B'
    """
    # decompose rho into blocks
    b1 = rho[:2, :2]
    b2 = rho[:2, 2:]
    b3 = rho[2:, :2]
    b4 = rho[2:, 2:]

    b12 = tf.concat([tf.transpose(b1), tf.transpose(b2)], axis=1)
    b34 = tf.concat([tf.transpose(b3), tf.transpose(b4)], axis=1)
    PT = tf.concat([b12, b34], axis=0)

    if subsys=='B':
        return PT
    elif subsys=='A':
        return tf.transpose(PT)

In [8]:
rho1 = tf.constant([[0, 1, 0, 1],
                    [0, 1, 0, 1],
                    [0, 1, 0, 1],
                    [0, 1, 0, 1]])

print(partial_transpose(rho1, subsys='B'))

tf.Tensor(
[[0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]], shape=(4, 4), dtype=int32)


In [9]:
def np_partial_transpose(rho, subsys='B'):
    """ 
    Helper function to compute the partial transpose of a density matrix. 
    Useful for the Peres-Horodecki criterion, which states that if the partial transpose 
    of a density matrix has at least one negative eigenvalue, then the state is entangled.
    
    Parameters:
        rho: density matrix
        subsys: which subsystem to compute partial transpose wrt, i.e. 'A' or 'B'
    """
    # decompose rho into blocks
    b1 = rho[:2, :2]
    b2 = rho[:2, 2:]
    b3 = rho[2:, :2]
    b4 = rho[2:, 2:]

    PT = np.array(np.block([[b1.T, b2.T], [b3.T, b4.T]]))

    if subsys=='B':
        return PT
    elif subsys=='A':
        return PT.T

In [10]:
rho2 = np.array([[0, 1, 0, 1],
                [0, 1, 0, 1],
                [0, 1, 0, 1],
                [0, 1, 0, 1]])

print(np_partial_transpose(rho2, subsys='B'))

[[0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]]
