This Jupyter notebook checks the witness values generated by states_and_witnesses.py against the witness expectation values as if they were hard-coded using the formulas from Paco's thesis. This is done using experimentally-obtained parameter values.

In [39]:
import numpy as np
import states_and_witnesses as sw

In [40]:
# Input the filename containing experimental data
filename = "ria_hd_negpi_3_va_trial7/rho_(hd_negpi_3_va-90.0-7).npy"

In [41]:
# Pauli Matrices
PAULI_X = np.array([[0,1], [1, 0]])
PAULI_Y = np.array([[0, -1j], [1j, 0]])
PAULI_Z = np.array([[1,0], [0,-1]])
IDENTITY = np.array([[1,0], [0,1]])

In [57]:
"""
The following functions get the "hard-coded" operator values of the W3s according to Paco's thesis
instead of doing calculations from first principles as the code does.
"""
def hard_W3_1(theta):
    return 0.25 * (np.kron(IDENTITY, IDENTITY) + np.kron(PAULI_Z, PAULI_Z) + np.cos(2*theta)*(np.kron(PAULI_X, PAULI_X) + np.kron(PAULI_Y, PAULI_Y)) + np.sin(2*theta)*(np.kron(PAULI_Z, IDENTITY) + np.kron(IDENTITY, PAULI_Z)))

def hard_W3_2(theta):
    return 0.25 * (np.kron(IDENTITY, IDENTITY) - np.kron(PAULI_Z, PAULI_Z) + np.cos(2*theta)*(np.kron(PAULI_X, PAULI_X) - np.kron(PAULI_Y, PAULI_Y)) + np.sin(2*theta)*(np.kron(PAULI_Z, IDENTITY) - np.kron(IDENTITY, PAULI_Z)))

def hard_W3_3(theta):
    return 0.25 * (np.kron(IDENTITY, IDENTITY) + np.kron(PAULI_X, PAULI_X) + np.cos(2*theta)*(np.kron(PAULI_Z, PAULI_Z) + np.kron(PAULI_Y, PAULI_Y)) + np.sin(2*theta)*(np.kron(PAULI_X, IDENTITY) + np.kron(IDENTITY, PAULI_X)))

def hard_W3_4(theta):
    return 0.25 * (np.kron(IDENTITY, IDENTITY) - np.kron(PAULI_X, PAULI_X) + np.cos(2*theta)*(np.kron(PAULI_Z, PAULI_Z) - np.kron(PAULI_Y, PAULI_Y)) - np.sin(2*theta)*(np.kron(PAULI_X, IDENTITY) - np.kron(IDENTITY, PAULI_X)))

def hard_W3_5(theta):
    return 0.25 * (np.kron(IDENTITY, IDENTITY) + np.kron(PAULI_Y, PAULI_Y) + np.cos(2*theta)*(np.kron(PAULI_Z, PAULI_Z) + np.kron(PAULI_X, PAULI_X)) + np.sin(2*theta)*(np.kron(PAULI_Y, IDENTITY) + np.kron(IDENTITY, PAULI_Y)))

def hard_W3_6(theta):
    return 0.25 * (np.kron(IDENTITY, IDENTITY) - np.kron(PAULI_Y, PAULI_Y) + np.cos(2*theta)*(np.kron(PAULI_Z, PAULI_Z) - np.kron(PAULI_X, PAULI_X)) - np.sin(2*theta)*(np.kron(PAULI_Y, IDENTITY) - np.kron(IDENTITY, PAULI_Y)))

In [58]:
# Load in experimental rho from the file
rho_E = np.load(filename, allow_pickle=True)[0]

def hard_expec_val(hard_val, rho):
    """
    A function to calculate an expectation value using the complex witness operator and complex rho instead
    of Stokes parameters.
    """
    return np.trace(hard_val @ rho)

In [59]:
# NOTE: Edit to set the parameter values
theta = 2.35644449

# Initialize a witness object to get the W3 expectation values from the code
W3_obj = sw.W3(rho=rho_E)

# W3_1
print("W3_1 value produced by code:", W3_obj.expec_val(1, theta))
print("W3_1 value produced by formula:", hard_expec_val(hard_W3_1(theta), rho_E))

# W3_2
print("\nW3_2 value produced by code:", W3_obj.expec_val(2, theta))
print("W3_2 value produced by formula:", hard_expec_val(hard_W3_2(theta), rho_E))

# W3_3
print("\nW3_3 value produced by code:", W3_obj.expec_val(3, theta))
print("W3_3 value produced by formula:", hard_expec_val(hard_W3_3(theta), rho_E))

# W3_4
print("\nW3_4 value produced by code:", W3_obj.expec_val(4, theta))
print("W3_4 value produced by formula:", hard_expec_val(hard_W3_4(theta), rho_E))

# W3_5
print("\nW3_5 value produced by code:", W3_obj.expec_val(5, theta))
print("W3_5 value produced by formula:", hard_expec_val(hard_W3_5(theta), rho_E))

# W3_6
print("\nW3_6 value produced by code:", W3_obj.expec_val(6, theta))
print("W3_6 value produced by formula:", hard_expec_val(hard_W3_6(theta), rho_E))

W3_1 value produced by code: 0.2533055205362819
W3_1 value produced by formula: (0.25330552053628197+0j)

W3_2 value produced by code: 0.23883216451870526
W3_2 value produced by formula: (0.23883216451870526+0j)

W3_3 value produced by code: 0.24748050320092568
W3_3 value produced by formula: (0.2474805032009257+2.6020852139652106e-18j)

W3_4 value produced by code: 0.24446321849567515
W3_4 value produced by formula: (0.24446321849567515+1.1275702593849246e-17j)

W3_5 value produced by code: 0.3490858217729125
W3_5 value produced by formula: (0.3490858217729125+0j)

W3_6 value produced by code: 0.15528153295238445
W3_6 value produced by formula: (0.15528153295238445+0j)


In [60]:
# Now compare the operators
# W3_1
print("W3_1 operator produced by code:", W3_obj.W3_1(theta))
print("W3_1 operator produced by formula:", hard_W3_1(theta))

# W3_2
print("\nW3_2 operator produced by code:", W3_obj.W3_2(theta))
print("W3_2 operator produced by formula:", hard_W3_2(theta))

# W3_3
print("\nW3_3 operator produced by code:", W3_obj.W3_3(theta))
print("W3_3 operator produced by formula:", hard_W3_4(theta))

# W3_4
print("\nW3_4 operator produced by code:", W3_obj.W3_4(theta))
print("W3_4 operator produced by formula:", hard_W3_4(theta))

# W3_5
print("\nW3_5 operator produced by code:", W3_obj.W3_5(theta))
print("W3_5 operator produced by formula:", hard_W3_5(theta))

# W3_6
print("\nW3_6 operator produced by code:", W3_obj.W3_6(theta))
print("W3_6 operator produced by formula:", hard_W3_6(theta))

W3_1 operator produced by code: [[6.24999025e-08+0.j 0.00000000e+00-0.j 0.00000000e+00+0.j
  0.00000000e+00+0.j]
 [0.00000000e+00+0.j 0.00000000e+00+0.j 2.49999797e-04+0.j
  0.00000000e+00-0.j]
 [0.00000000e+00-0.j 2.49999797e-04+0.j 0.00000000e+00+0.j
  0.00000000e+00+0.j]
 [0.00000000e+00+0.j 0.00000000e+00+0.j 0.00000000e+00-0.j
  9.99999938e-01+0.j]]
W3_1 operator produced by formula: [[6.24999025e-08+0.j 0.00000000e+00+0.j 0.00000000e+00+0.j
  0.00000000e+00+0.j]
 [0.00000000e+00+0.j 0.00000000e+00+0.j 2.49999797e-04+0.j
  0.00000000e+00+0.j]
 [0.00000000e+00+0.j 2.49999797e-04+0.j 0.00000000e+00+0.j
  0.00000000e+00+0.j]
 [0.00000000e+00+0.j 0.00000000e+00+0.j 0.00000000e+00+0.j
  9.99999938e-01+0.j]]

W3_2 operator produced by code: [[0.00000000e+00+0.j 0.00000000e+00+0.j 0.00000000e+00-0.j
  2.49999797e-04+0.j]
 [0.00000000e+00-0.j 6.24999025e-08+0.j 0.00000000e+00+0.j
  0.00000000e+00+0.j]
 [0.00000000e+00+0.j 0.00000000e+00+0.j 9.99999938e-01+0.j
  0.00000000e+00-0.j]
 [2.499

In [46]:
"""
"Hard-coded" operator values of the W5s.
"""
def hard_W5_1(theta, alpha):
    return 0.25 * (np.kron(IDENTITY, IDENTITY) + np.kron(PAULI_Z, PAULI_Z) + np.cos(2*theta)*(np.cos(alpha)*(np.kron(PAULI_X, PAULI_X) + np.kron(PAULI_Y, PAULI_Y)) - np.sin(alpha)*(np.kron(PAULI_X, PAULI_Y) - np.kron(PAULI_Y, PAULI_X))) + np.sin(2*theta)*(np.kron(PAULI_Z, IDENTITY) + np.kron(IDENTITY, PAULI_Z)))

In [52]:
# NOTE: Edit to set the parameter values
theta = 1.57079633
alpha = 1.57079632
beta = 1.49644255

# Initialize a witness object to get the W5s from the code
W5_obj = sw.W5(rho=rho_E)

# W5_1
print("W5_1 operator produced by code:", W5_obj.W5_1(theta, alpha))
print("W5_1 operator produced by formula:", hard_W5_1(theta, alpha))

W5_1 operator produced by code: [[ 4.99999997e-01+2.77555756e-17j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
  -3.39744835e-09+5.00000000e-01j  0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j -3.39744835e-09-5.00000000e-01j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  5.00000003e-01+0.00000000e+00j]]
W5_1 operator produced by formula: [[ 4.99999997e-01+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j
   0.00000000e+00+0.j ]
 [ 0.00000000e+00+0.j   0.00000000e+00+0.j  -3.39744835e-09+0.5j
   0.00000000e+00+0.j ]
 [ 0.00000000e+00+0.j  -3.39744835e-09-0.5j  0.00000000e+00+0.j
   0.00000000e+00+0.j ]
 [ 0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j
   5.00000003e-01+0.j ]]


In [53]:
np.kron(IDENTITY, IDENTITY)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [54]:
np.kron(PAULI_Z, PAULI_Z)

array([[ 1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0,  1]])

In [55]:
np.kron(PAULI_X, PAULI_X)

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [56]:
np.kron(PAULI_Y, PAULI_Y)

array([[ 0.+0.j,  0.-0.j,  0.-0.j, -1.+0.j],
       [ 0.+0.j,  0.+0.j,  1.-0.j,  0.-0.j],
       [ 0.+0.j,  1.-0.j,  0.+0.j,  0.-0.j],
       [-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]])